login/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    #URLS HOME
    # path('', views.home_login, name='principal'),
    path('', views.home_login, name='login'),
    path('registeroption',views.register_option, name='registeroption'),
    path('taller',views.taller,name='taller'),
    path('cliente',views.cliente, name='cliente'),
    path('login/registration/login.html', views.home_login, name='login'),   

    #URLS CLIENTES
    path('calendario', views.clientes_calendario, name='ccalendario'),
    path('talleres',views.clientes_talleres, name='ctalleres'),
        path('eliminar_opinion/<int:opinion_id>/', views.eliminar_opinion, name='eliminar_opinion'),
        path('reservar/<str:taller_name>/', views.reservar_cita, name='reservar_cita'),
        path('editar_opinion/<int:opinion_id>/', views.editar_opinion, name='editar_opinion'),
    path('vehiculos',views.clientes_vehiculos, name='cvehiculos'),
        path('eliminar_vehiculo/<int:vehiculo_id>/', views.eliminar_vehiculo, name='eliminar_vehiculo'),  
        path('edit',views.clientes_edit, name='cperfil'),
    path('cancelar_cita/<int:reserva_id>/', views.cancelar_cita, name='cancelar_cita'),


    #URLS TALLERES
    path('analitica', views.talleres_analitica, name='tanalitica'),
    path('citas',views.talleres_citas, name='tcalendario'),
    path('servicios',views.talleres_servicios, name='tservicios'),
    path('notificacion',views.talleres_notificacion, name='tnotificaciones'),
    path('perfil',views.talleres_edit, name='tperfil'),
    path('agendar/<str:taller_name>/', views.agendar_citas, name='agendar_citas'),
    path('editar_servicio/<int:servicio_id>/', views.editar_servicio, name='editar_servicio'),
    path('eliminar_servicio/<int:servicio_id>/', views.eliminar_servicio, name='eliminar_servicio'),



    
    path('cambiar_estado_cita/<int:cita_id>/<str:nuevo_estado>/', views.cambiar_estado_cita, name='cambiar_estado_cita'),

    
    
    path('actualizar_vehiculo/<int:vehiculo_id>/', views.actualizar_vehiculo, name='actualizar_vehiculo'),
    path('reservar/<str:taller_name>/', views.reservar_cita, name='reservar_cita'),


    #URLS PASSWORD RESET
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #path('login/', auth_views.LoginView.as_view(), name='login'),

]
    

mechanicsrevolution/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView


urlpatterns = [
    path('',include('login.urls')),
    path('admin/', admin.site.urls),
    path('404/', TemplateView.as_view(template_name='404.html'), name='error_404'),
    path('login/',include('login.urls'))
]

login/models.py
from django.db import models
from django.contrib.auth.models import User

#USUARIOS
class ExtendedData(models.Model):
    telefono = models.CharField(max_length=10, null=True,blank=True)
    direccion = models.CharField(max_length=128, null=True,blank=True)
    cp = models.CharField(max_length=5, null=True,blank=True)
    calidad = models.IntegerField(default=0,blank=True,null=True)
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE,blank=True)
    descripcion = models.CharField(max_length=300, null=True,blank=True)


#Vehículos
class Vehiculos(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    TIPOS_CHOICES = [
        ('carro', 'Carro'),
        ('bicicleta', 'Bicicleta'),
        ('moto', 'Moto'),
    ]
    tipo = models.CharField(max_length=10, choices=TIPOS_CHOICES)
    modelo = models.CharField(max_length=10, null=True, blank=True)
    año = models.IntegerField(default=0, blank=True, null=True)

#Servicios
class Service(models.Model):
    SERVICE_CHOICES = [
        ('Mantenimiento', 'Mantenimiento'),
        ('Cambio de aceite', 'Cambio de aceite'),
        ('Frenos', 'Frenos'),
        ('Suspensión', 'Suspensión'),
    ]

    TIME_CHOICES = [
        ('1', '1 hora'),
        ('2', '2 horas'),
        ('3', '3 horas'),
        ('4', '4 horas'),
        ('5', '5 horas'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    service_name = models.CharField(max_length=50, choices=SERVICE_CHOICES)
    service_time = models.CharField(max_length=1, choices=TIME_CHOICES)
    service_price = models.DecimalField(max_digits=10, decimal_places=2)

#OPINIONES
class Opinion(models.Model):
    id_taller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='opinions')
    id_usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    opinion = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    #variable sentimiento
    sentimiento = models.CharField(max_length=10, blank=True, null=True, choices=(
        ('alegre', 'Alegre'),
        ('triste', 'Triste'),
        ('neutro', 'Neutro'),
        ('enojado', 'Enojado')
    ))
    class Meta:
        unique_together = ['id_taller', 'id_usuario']

#RESERVAR CITA
class ReservaCita(models.Model):
    taller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservas_como_taller')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservas_como_usuario')
    fecha = models.DateField()
    hora_entrega = models.TimeField()
    vehiculo = models.ForeignKey(Vehiculos, on_delete=models.CASCADE)
    servicio = models.ForeignKey(Service, on_delete=models.CASCADE)
    ESTATUS_CHOICES = (
        ('Agendada', 'agendada'),
        ('Cancelada', 'cancelada'),
        ('En espera de entrega de vehículo', 'en espera de entrega de vehículo'),
        ('En progreso', 'en progreso'),
        ('En espera de recogida de vehículo', 'en espera de recogida de vehículo'),
        ('Terminada', 'terminada'),
    )

    estatus = models.CharField(max_length=50, choices=ESTATUS_CHOICES, default='Agendada')

    def __str__(self):
        return f'Reserva para {self.taller.username} - {self.usuario.username}'
    

login/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.urls import reverse
from django.db.models import F

from django.http import JsonResponse

from django.utils import timezone
from django.contrib.auth.models import User

from pathlib import Path
from .forms import *
from .models import *

from azure.core.credentials import AzureKeyCredential
from azure.ai.textanalytics import TextAnalyticsClient

from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

# Create your views here.

############################################################LOGIN############################################################
# VISTA PARA EL LOGIN
def home_login(request):
    error_message = ""  
    print(Path(__file__).resolve().parent.parent)
    if request.method == 'POST':
        correo = request.POST.get('correo')
        contrasena = request.POST.get('contrasena')

        if correo and contrasena:
            user = authenticate(request, username=correo, password=contrasena)

            if user is not None:
                try:
                    usuario_extendido = user.extendeddata
                    if usuario_extendido.cp:
                        login(request, user)
                        return redirect('tanalitica')
                    else:
                        login(request, user)
                        return redirect('ctalleres')
                except ExtendedData.DoesNotExist:
                    pass
            else:
                error_message = 'Usuario o contraseña incorrecto'  

        if not correo or not contrasena:
            error_message = 'Por favor, complete todos los campos'

    return render(request, 'registration/login.html', {'error_message': error_message})


#PINTAR PÁGINA DE SI ERES TALLER O CLIENTE
def register_option(request):
    return render(request,'registeroption.html')

#VISTA PARA REGISTRAR TALLER
def taller(request):
    error_message = ""
    if request.method == 'POST':
        user_form = createUserForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)
        print(user_form.errors)
        print(user_profile_form.errors)
        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save() 
            profile = user_profile_form.save(commit=False)  
            profile.user = user
            profile.save()
            return redirect('login')
        else:
            error_message = "El usuario que ingresó ya existe intente con otro"
    else:
        user_form = createUserForm()
        user_profile_form = UserProfileForm()

    data_context = {'user_form': user_form, 'user_profile_form': user_profile_form, 'error_message': error_message}
    return render(request, 'taller.html', data_context)

#VISTA PARA REGISTRAR CLIENTE
def cliente(request):
    error_message = ""
    user_form = createUserForm()
    user_profile_form = UserProfileForm()
    data_context = {'user_form': user_form, 'user_profile_form': user_profile_form}
    
    if request.method == 'POST':
        user_form = createUserForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)
        print(user_form.errors)
        print(user_profile_form.errors)
        
        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save() 
            profile = ExtendedData()
            profile.telefono = request.POST['telefono']
            profile.user = user
            profile.save()
            return redirect('login')
        else:
            error_message = "El usuario que ingresó ya existe intente con otro."

    data_context['error_message'] = error_message
    return render(request, 'cliente.html', data_context)

#RECUPERAR COMNTRASEÑA

class CustomPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = reverse_lazy('password_reset_complete')

############################################################LOGIN############################################################



############################################################CLIENTES############################################################

#LISTA DE TALLERES
@login_required
def clientes_talleres(request):
    talleres = ExtendedData.objects.exclude(cp__isnull=True).exclude(cp__exact='')
    return render(request, 'clientes_talleres.html', {'talleres': talleres})

#LISTA DE CITAS
@login_required
def clientes_calendario(request):
    citas = ReservaCita.objects.filter(usuario=request.user).annotate(taller_name=F('taller__username'))
    return render(request, 'clientes_calendario.html', {'citas': citas})

#EDITAR PERFIL
@login_required
def clientes_edit(request):
    user = request.user
    extended_data, created = ExtendedData.objects.get_or_create(user=user)
    show_alert = False  
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            correo = form.cleaned_data['email']
            telefono = form.cleaned_data['telefono']
            if created:
                extended_data = ExtendedData.objects.create(user=user, telefono=telefono)
            else:
                extended_data.telefono = telefono
                extended_data.save()
            user.email = correo
            user.save()
            messages.success(request, 'Perfil actualizado correctamente') 
            show_alert = True
    else:
        initial_data = {'telefono': extended_data.telefono} if extended_data else None
        form = UserEditForm(instance=user, initial=initial_data)
    return render(request, 'clientes_edit.html', {'form': form, 'extended_data': extended_data, 'user': user, 'show_alert': show_alert})

#Lista vehículos
@login_required
def clientes_vehiculos(request):
    if request.method == 'POST':
        form = VehiculoForm(request.POST)
        if form.is_valid():
            vehiculo = form.save(commit=False)
            vehiculo.usuario = request.user
            vehiculo.save()
            return redirect('cvehiculos')
    else:
        form = VehiculoForm()

    vehiculos = Vehiculos.objects.filter(usuario=request.user)

    # Vehiuclo borrado
    if request.GET.get("vehicle_deleted") == "true":
        messages.success(request, "Vehículo eliminado.")

    return render(request, 'clientes_vehiculos.html', {'form': form, 'vehiculos': vehiculos})

# Eliminación de vehículos
@login_required
def eliminar_vehiculo(request, vehiculo_id):
    vehiculo = get_object_or_404(Vehiculos, pk=vehiculo_id)

    if request.method == "POST":
        vehiculo.delete()
        messages.success(request, "Vehículo eliminado.")

    return redirect('cvehiculos')

#EDITAR VEHÍCULO
@login_required
def actualizar_vehiculo(request, vehiculo_id):
    vehiculo = Vehiculos.objects.get(id=vehiculo_id)

    if request.method == 'POST':
        form = VehiculoForm(request.POST, instance=vehiculo)
        if form.is_valid():
            form.save()
            return redirect('cvehiculos') 
    else:
        form = VehiculoForm(instance=vehiculo)

    return render(request, 'editar_vehiculo.html', {'form': form})


def editar_vehiculo(request, vehiculo_id):
    vehiculo = get_object_or_404(Vehiculos, id=vehiculo_id)
    if request.method == 'POST':
        form = VehiculoForm(request.POST, instance=vehiculo)
        if form.is_valid():
            form.save()
            return redirect('cvehiculos')
    else:
        form = VehiculoForm(instance=vehiculo)

    return render(request, 'nombre_del_template_editar_vehiculo.html', {'form': form})

#PERFIL DE TALLERES
@login_required
def agendar_citas(request, taller_name):
        taller = get_object_or_404(ExtendedData, user__username=taller_name)
        servicios = Service.objects.filter(user=taller.user)
        if request.method == 'POST':
            # Procesa el formulario de creación de opiniones
            try:
                id_taller = User.objects.get(username=taller_name)
                opinion_text = request.POST.get('opinion')
                id_usuario = request.user
                opinion = Opinion(id_taller=id_taller, id_usuario=id_usuario, opinion=opinion_text)
                opinion.save()
                # Realiza el análisis de sentimiento
                credential = AzureKeyCredential("6e222a611092490ca0462c4a0a436616")
                endpoint = "https://lenguajedsccacg.cognitiveservices.azure.com/"
                text_analytics_client = TextAnalyticsClient(endpoint,credential)
                documents = [opinion_text]
                response = text_analytics_client.analyze_sentiment(documents, language="es")
                result = response[0]
                # Después de obtener el resultado del análisis de sentimiento
                sentimiento_mapping = {
                    'positive': 'alegre',
                    'negative': 'triste',
                    'neutral': 'neutro'
                }
                opinion.sentimiento = sentimiento_mapping.get(result.sentiment)
                opinion.save()
                # Guarda el sentimiento en la opinión
                # opinion.sentimiento = result.sentiment
                # opinion.save()
                print("Opinión guardada exitosamente.")
            except Exception as e:
                print("Error al guardar la opinión:", str(e))
        opiniones = Opinion.objects.filter(id_taller=taller.user)
        return render(request, 'citas.html', {'taller': taller, 'servicios': servicios, 'opiniones': opiniones, 'taller_name': taller_name,})

#CONTABILIZAR SENTIMIENTOS
def contar_sentimientos(user):
    opiniones = Opinion.objects.filter(id_taller=user.taller.id)  

login/templates/editar_servicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'style.css' %}"> <!-- Enlaza a tu archivo CSS local -->
  <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
  <link rel="shortcut icon" href="{% static 'images/logo.png' %}">
  <title>Mechassit</title>
  <style>
      @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap");
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: "Poppins", sans-serif;
    }

    :root {
      /* ===== Colors ===== */
      --body-color: #18191a;
      --sidebar-color: #242526;
      --primary-color: #0094FF;
      --primary-color-light: #3a3b3c;
      --text-color: #fff; /* Cambio de color de texto a blanco */
      /* ====== Transition ====== */
      --tran-03: all 0.2s ease;
      --tran-04: all 0.3s ease;
      --tran-05: all 0.3s ease;

      --border-radius: 6px;
    }

    body {
      min-height: 100vh;
      background-color: var(--body-color);
      transition: var(--tran-05);
    }

    ::selection {
      background-color: var(--primary-color);
      color: #fff;
    }
    .edit-service-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .edit-service-form {
      background-color: #f9f9f9;
      border-radius: 8px;
      padding: 40px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      width: 35%;
    }

    .edit-service-form h2 {
      text-align: center;
      font-size: 24px;
    }

    .form-group {
      margin: 10px 0;
    }

    .form-group label {
      display: block;
      color: #333;
    }

    .form-group input,
    .form-group select {
      width: 100%; /* This will make the input fields and dropdowns fill the container */
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      background-color: #f9f9f9;
      color: #333;
      outline: none;
      display: block; /* This ensures that the width is respected */
      margin: auto; /* This will center the inputs if the container has a defined width */
    }

    .btn-primary {
      background-color: #242526;
      color: #fff;
      border: none;
      border-radius: 8px;
      padding: 10px 20px;
      cursor: pointer;
      font-size: 16px;
      margin-top: 10px;
      display: block;
      width: fit-content;
      margin: 10px auto;
    }

    .btn-primary:hover,
    .btn-primary:active {
        background-color: #0094FF; /* Color verde cuando se pasa el cursor por encima */
        /* ... Cualquier otro estilo que desees aplicar al pasar el cursor ... */
    }

    .error-message {
      color: #ff4d4f;
      margin-top: 10px;
      font-size: 14px;
    }

    .link-secondary {
      color: #0094FF;
      text-decoration: none;
      padding: 10px 20px;
      display: inline-block; /* Para que los paddings funcionen */
      margin-top: 10px; /* Espacio por encima del enlace */
    }

    .back-link {
      display: block; /* El enlace se muestra como bloque para permitir centrarlo */
      margin: 10px auto; /* Centra el enlace horizontalmente */
      text-align: center; /* Asegura que el texto dentro del enlace esté centrado */
      text-decoration: underline; /* Subraya el enlace */
      color: #0276c9; /* Color azul para el enlace */
      padding: 10px; /* Espacio alrededor del enlace para hacerlo más fácil de clickear */
    }

    .back-link:visited {
      color: #800080; /* Color morado para el enlace una vez visitado */
    }

    .open-button {
      background-image: url('https://cdn-icons-png.flaticon.com/512/4712/4712126.png'); /* Path to your bot image */
      background-color: #18191a;
      background-size: contain; /* Or 'cover' if you want the image to fully cover the button */
      background-position: center;
      background-repeat: no-repeat; /* Prevent the image from repeating */
      color: transparent; /* Hide the text */
      border: none;
      cursor: pointer;
      /* opacity: 0.8; */
      position: fixed;
      bottom: 23px;
      right: 30px;
      width: 80px; /* Adjust to the size you want */
      height: 80px; /* Adjust to the size you want */
      overflow: hidden; /* Hide any overflow */
      z-index: 1; /* This should be higher than the .open-button's z-index */
    }

    .open-button.chat-open {
      display: none;
    }


    .chat-popup {
      display: none; /* Initially hidden */
      position: fixed;
      bottom: 0px; /* Position it above the bot image; adjust as needed */
      right: 30px; /* Align with the right side of the bot image */
      width: 340px; /* Adjust as needed */
      height: 520px;
      border: none;
      z-index: 15; /* Above the bot image */
      border-radius: 20px; /* Rounded corners for the chat bubble */
      box-shadow: none; /* Optional: adds a shadow for depth */
    }

    .chat-popup::before {
      content: '';
      position: absolute;
      bottom: -20px; /* Position the triangle just below the chat window */
      right: 50px; /* Position the triangle to point towards the bot image */
      width: 0;
      height: 0;
      border-left: 20px solid transparent;
      border-right: 20px solid transparent;
      border-top: 20px solid white; /* Color of the thought bubble */
      border-top-color: #FFFFFF;
    }

.chatbot-window {
  min-height: 410px;  
}

.btn_cancel {
  background-image: url('https://cdn-icons-png.flaticon.com/512/4712/4712010.png'); /* Path to your bot image */
  background-color:  #18191a;
  background-size: contain; /* Or 'cover' if you want the image to fully cover the button */
  background-position: center;
  background-repeat: no-repeat; /* Prevent the image from repeating */
  color: transparent; /* Hide the text */
  border: none;
  cursor: pointer;
  /* opacity: 0.8; */
  position: fixed;
  bottom: 23px;
  right: 30px;
  width: 80px; /* Adjust to the size you want */
  height: 80px; /* Adjust to the size you want */
  overflow: hidden; /* Hide any overflow */
}

  </style>
</head>
<button class="open-button" onclick=openForm()>Exchange Bot!</button>

    <div class="chat-popup" id="chatbotpanel">
        <form class="form-chatbot" > 
          <iframe class = "chatbot-window" src='https://webchat.botframework.com/embed/lenguajeUMFA-bot?s=Z9OF1TgOblM.9jnrAMNseuDItmzlUPdXwGbgf8N4fXed6kQJCgLfVmo'></iframe>
          <button type="button" class="btn_cancel" onclick=closeForm()>Cerrar Bot</button>
        </form>
    </div>
<body>

  <section class="home">
    <div class="container">
      <div class="edit-service-container">
        <form method="post" class="edit-service-form">
          <h2 style="color: #0094FF;">Editar Servicio</h2>
          <br>
          {% csrf_token %}
          <div class="form-group">
            <label for="id_service_name"><b>Nombre del Servicio:</b></label>
            {{ form.service_name }}
          </div>
          <div class="form-group">
            <label for="id_service_time"><b>Tiempo de Servicio:</b></label>
            {{ form.service_time }}
          </div>
          <div class="form-group">
            <label for="id_service_price"><b>Precio del Servicio:</b></label>
            {{ form.service_price }}
          </div>
          <br>
          <button type="submit" class="btn btn-primary">Guardar Cambios</button>
          <a href="javascript:history.back();" class="back-link">Regresar</a>
        </form>
      </div>
      {% if error_message %}
      <div class="error-message">{{ error_message }}</div>
    {% endif %}
    </div>
  </section>
   <!-- BotScript files-->
 <script>
  function openForm() {
    document.getElementById("chatbotpanel").style.display = "block";
    document.getElementById('open-button').classList.add('chat-open');
  }

  function closeForm() {
    document.getElementById("chatbotpanel").style.display = "none";
    document.getElementById('open-button').classList.remove('chat-open');
  }
</script>
</body>
</html>

login/templates/home_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Mechassit</title>
<link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
<link rel="shortcut icon" href="{% static 'images/logo.png' %}">
<style>
  @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap");
  * { box-sizing: border-box; }
  
  body {
    font-family: "Poppins", sans-serif;
    margin: 0;
    padding: 0;
    background-image: url(https://images.unsplash.com/photo-1525841508523-2aebc593a6b7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1932&q=80);
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
  }

  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
  }

  .left {
    background-color: rgba(0, 0, 0, 0.5);
    padding: 20px;
    border-radius: 10px;
    text-align: center;
    color: white;
  }

  .form-field {
    height: 40px;
    padding: 10px;
    border: none;
    border-radius: 6px;
    font-size: 16px;
    background-color: rgba(255, 255, 255, 0.8);
    margin-top: 15px;
    color: black;
  }

  .form-field:focus {
    outline: none;
    background-color: rgba(255, 255, 255, 1);
  }

  .form > button {
    padding: 10px 20px;
    border: none;
    background: #0f7ef1;
    border-radius: 6px;
    margin-top: 15px;
    color: white;
    font-size: 16px;
    letter-spacing: 1px;
    cursor: pointer; /* Cambia el cursor al pasar sobre el botón */
  }
</style>
</head>
<body>
  <div class="container">
    <div class="left">
      <div class="header">
        <h2 class="animation a1">Bienvenido</h2>
        <h4 class="animation a2">Ingresa a Mechanics Revolution</h4>
      </div>
      <form method="post" action="">
        {% csrf_token %}
        <div class="form">
          <input type="Correo" id="correo" name="correo" class="form-field animation a3" placeholder="Correo" autocomplete="off">
          <input type="password" id="contrasena" name="contrasena"  class="form-field animation a4" placeholder="Contraseña" autocomplete="off">
          <button type="submit" class="animation a6">LOGIN</button>
          <p>{{error_message}}</p>
          <div class="animation a5">
            <br>
            <a href="registeroption" style="color: #0f7ef1; margin-right: 20px;">Registrarse</a>
            <a href="registeroption" style="color: #0f7ef1;">Olvidé contraseña</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</body>
</html>